### ISSUE TITLE
[Bug]: Dynamic column resizing issue in 'More Information' section

### ISSUE THREAD

**Issue by karenroldan** [Automattic/bugomattic#112]
### Quick summary

Layout issue in the 'More Information' section in the `Next Steps` step. The first column occupies a lot of space when the description is lengthy.

### Steps to reproduce

1. Fill out the details on 'Type' and 'Product and Feature' until you reach the 'Next Steps' step. 
2. Enter a lengthy description on the feature group. 
3. Observe that it reduces the space allocated for content in the feature. 

![Screenshot 2023-06-01 at 16 03 02](https://github.com/Automattic/bugomattic/assets/67279475/d01b8c50-46fd-47e3-80c7-e468647ee893)

![Screenshot 2023-06-01 at 16 03 29](https://github.com/Automattic/bugomattic/assets/67279475/a027679c-9ffc-4c51-878b-6d918c330f66)

### Browser

Google Chrome/Chromium

**Comment by dpasque** [comment]
Fixed by #114
