### ISSUE TITLE
[Task]: Add all default labels for WordPress and Jetpack issues

### ISSUE THREAD

**Issue by dpasque** [Automattic/bugomattic#118]
### Details

Tweak the script we're using so that issues in WordPress and Jetpack have the labels added by default by the templates.

E.g. "[Type] Bug":
https://github.com/Automattic/wp-calypso/issues/new?assignees=&labels=Needs+triage%2C+%5BType%5D+Bug%2C+User+Report&projects=&template=bug_report.yml

### Checklist

- [ ]

**Comment by karenroldan** [comment]
Changes can be found here: https://github.com/Automattic/bugomattic/commit/a6118ef7f0285ce6e7173fcac37c1b6f9194c62e

Key changes:
1. The following labels are added for bug & urgent tasks: '[Type] Bug', 'Needs triage', 'User Report'
2. The label '[Type] Feature Request' is added for feature request tasks
