### ISSUE TITLE
[Task]: Tweak copy for Next Steps v2

### ISSUE THREAD

**Issue by karenroldan** [Automattic/bugomattic#130]
### Details

Context: pdtkmj-1wK-p2#comment-2773

This is a placeholder until we come up with a clearer copy for Next Steps! 

One of the suggestions: 
- Click here to open your GitHub report. Don’t forget to click the “Submit new issue” button! [GITHUB BUTTON]

### Checklist

- [ ]

**Comment by dpasque** [comment]
We did this during the CfT! 🚀
