### ISSUE TITLE
[Task]: Redesign the task checklists, v2

### ISSUE THREAD

**Issue by dpasque** [Automattic/bugomattic#132]
### Details

Context: pdtkmj-1wK-p2#comment-2773, p1687449922021919-slack-CQD1HH4MA

The checkboxes are throwing some folks off!

It seems to be a combo of...
- The checkbox itself isn't really tied to an action
- It's on the left, so it's first thing you read

We should see if we can find away to maybe get rid of the confusing checkbox while keeping the list like a checkbox with the ability to mark things as done.

Perhaps we could remove the checkbox, make the whole card a link, and when they click it, add a green border and checkmark?

We also need to make sure we account for tasks that don't have a link.

### Checklist

- [ ]

**Comment by dpasque** [comment]
cc @john-legg as we might need some designer help on this one! 😅

**Comment by dpasque** [comment]
I had one idea today!

I don't really have any mock-up tool chops to make this easily heheh, but...

What if we....
1. Removed the CTA and just made the whole card a link
2. Replace the current checkbox with the icon designating the kind of link (and we can use some icon for linkless tasks)
3. When you click the card/link, and we mark the task as completed, we replace that icon with a green checkmark

Might work? Might be stupid? 🤷

**Comment by john-legg** [comment]
@dpasque I think that's a great idea actually! I started a Slack thread with a few mockups to look at: p1687814809689709/1687449922.021919-slack-CQD1HH4MA

**Comment by dpasque** [comment]
This has been updated and fixed!
