### ISSUE TITLE
Error when loading the reporting config

### ISSUE THREAD

**Issue by karenroldan** [Automattic/bugomattic#147]
### Quick summary

Context: pb6Nl-gEx-p2#comment-103208

```
QuotaExceededError: Failed to execute 'setItem' on 'Storage': Setting the value of 'cachedReportingConfigData' exceeded the quota.
``` 

### Steps to reproduce

1. Store more than the allocated space in the local storage of the browser
2. Load Bugomattic 
3. A message "Uh oh! Something went strong :(" will be displayed.

**Comment by dpasque** [comment]
Btw, here are the current sizes of our localstorage:

```
cachedReportingConfigData = 356.29 KB
repoFilters = 1.17 KB
repoFiltersExpiry = 0.06 KB
grafana.sectionNav.expanded = 0.06 KB
cacheExpiry = 0.05 KB
Total = 357.63 KB
```

More browsers limit to 5000 KB per domain by default, so we're well below that, but folks may have smaller limits configured, and I think there are overall limits.

All that to say, we should probably just start with a try-catch! It's just a cache, so we should never let that block using the site

**Comment by dpasque** [comment]
Internally, we're basically sharing with every other internal tool site on the main MC domain, so that's why some folks may hit it. 🤷
