### ISSUE TITLE
Add Woo Express category and keyword.

### ISSUE THREAD

**Issue by worldomonation** [Automattic/bugomattic#157]
### Quick summary

I tried to report an issue for Woo Express but the category search did not return a matching repo.

Ultimately I ended up reporting it at Automattic/woocommerce repo, as there were existing Woo Express issues there.

### Steps to reproduce

1. open Bugomattic.
2. click on "Report an issue".
3. search for Woo Express.

**Comment by jeherve** [comment]
Looks like this was already done; the reports go to the Calypso repo today. Closing.
