### ISSUE TITLE
[Feature Request]: More keywords for [Feature] Site Content Emails 

### ISSUE THREAD

**Issue by cuemarie** [Automattic/bugomattic#158]
### "What": What is your idea?

We could stand to beef up the keywords (and maybe other support links) under this label in Bugomattic to help HEs find this new label. Currently, the only key words are:

![Markup on 2023-08-09 at 13:49:01](https://github.com/Automattic/bugomattic/assets/27249804/7c0b4a77-c3aa-4b07-8417-e93705eb643e)

Some ideas, based on how HEs often talk about this issue:

`New Post`, `New Post Emails`, `Email Notifications`, `Following`, `Followers`

### "Why?": Why would this be impactful?

Site Content emails, ie new post emails that site followers/subscribers get, is a pretty common issue that customers contact us about, since they have no control over how those look.  We haven't had strong unifying language around this feature - and it is also (or in the past, was) powered by Jetpack, so HEs could end up filing these issues under Jetpack based on that understanding.

**Comment by jeherve** [comment]
Done in D129579-code.
