### ISSUE TITLE
More keywords for SEO Tools feature

### ISSUE THREAD

**Issue by cuemarie** [Automattic/bugomattic#159]
### "What": What is your idea?

Add more keywords that encompass our different SEO tools to the SEO tools bugomattic result. Specifically, I was looking for "Sitemaps" today

### "Why?": Why would this be impactful?

Right now, searching for `sitemaps` in bugomattic turns up no results. 

### "How?" How should this feature work?

We can probably expand our list of SEO Tools keywords beyond `sitemaps` too - right now it's pretty slim:

![t1bLb8.png](https://github.com/Automattic/bugomattic/assets/27249804/b6009fbc-5ba5-4e77-8114-a3ab9ee10a4c)

**Other Ideas to add:**

`search engines`
`page title structure`
`google analytics`
`related posts`
`shortlinks`
`sitemaps`
`site verification`

**Comment by jeherve** [comment]
Done in D128235-code
