### ISSUE TITLE
Add Page Optimize to repo filtering and search terms

### ISSUE THREAD

**Issue by cuemarie** [Automattic/bugomattic#161]
### Quick summary

We're missing Page Optimize from Bugomattic! :) 

### Steps to reproduce

Try to report a bug in Bugomattic about Page Optimize - no search results in bug reporting recommendations

**Comment by jeherve** [comment]
- https://github.com/Automattic/page-optimize/commit/82e97904c14f0fc113720f8adef33602475cd66c added the necessary templates and automations to the repo
- I added the necessary labels and secrets to the repo
- D129588-code adds the config to Bugomattic.
