### ISSUE TITLE
[Feature Request]: Add "Categories and Tags" feature under Content Management feature group

### ISSUE THREAD

**Issue by cuemarie** [Automattic/bugomattic#162]
### "What": What is your idea?

I've created [[Feature] Categories and Tags](https://github.com/Automattic/wp-calypso/labels/%5BFeature%5D%20Categories%20and%20Tags) in `wp-calypso`, but we'll want to add that to Bugomattic as it's own item as well.

See: p1696537274239589-slack-CQD1HH4MA

### "Why?": Why would this be impactful?

To better track issues with categories and tags, which aren't quite the same as page/post editor issues. 

### "How?" How should this feature work?

- [Feature Group] Content Management
     - [Feature] Categories and Tags

**Comment by karenroldan** [comment]
Would be fixed by D124518-code. 

@cuemarie  I used `[Feature] Categories & Tags` instead of `and` for consistency on other labels & features.
Are you okay with updating the label from `and` to `&`?

**Comment by cuemarie** [comment]
>Are you okay with updating the label from and to &?

Done! Thank you!

**Comment by karenroldan** [comment]
Fixed by D124518-code 🎈
