### ISSUE TITLE
[Task]: Update Support Sessions category

### ISSUE THREAD

**Issue by allilevine** [Automattic/bugomattic#164]
### Details

Choosing the Support Sessions category takes you to Automattic/support-session but that repo is inactive and unmonitored. See p1697260404758229/1696649426.788599-slack-C9EJ7KSGH

The better way to get help with Support Sessions on Atomic would be to ping in the `#atomic` Slack channel as far as I can tell.

### Checklist

- [ ] Update next actions for Support Sessions bugs.

**Comment by jeherve** [comment]
Done in D129581-code.
