### ISSUE TITLE
Add the WordPress.com forums as a feature under Support

### ISSUE THREAD

**Issue by cometgrrl** [Automattic/bugomattic#165]
### "What": What is your idea?

See p1698081556859809-slack-CQD1HH4MA for more context.  Issues should be filed to `wp-calypso` repo.

### "Why?": Why would this be impactful?

The forums are currently missing from Bugomattic.

**Comment by cometgrrl** [comment]
Once this is done, please let @cuemarie know so Kat Squad can review open issues from https://github.com/Automattic/lighthouse-forums and move them over as appropriate.

**Comment by jeherve** [comment]
Done in D129582-code. @cuemarie You should be good to go. I created a matching label in the Calypso repo for the forums.
