### ISSUE TITLE
[Feature Request]: Add new label under Support Feature Group: [Feature] Support Links 

### ISSUE THREAD

**Issue by cuemarie** [Automattic/bugomattic#166]
### "What": What is your idea?

Add a new label to Bugomattic for issues related to links to support docs all around Calypso. These don't really fall under any of the existing Feature labels we offer under `[Feature Group] Support`, which include:

- Help Center
- Support Docs Content
- Support Docs Site & Infrastructure

![Screenshot on 2023-10-25 at 10-19-02](https://github.com/Automattic/bugomattic/assets/27249804/a05fa6dc-e448-46f2-b409-d8bfbbb7ae0b)

### "Why?": Why would this be impactful?

We see lots of requests to update a specific link on a particular page. Instead of filing these under the page in question, it'd make more sense (and be much faster) to just file them all under a `[Feature] Support Links` label

**Comment by cuemarie** [comment]
Example issue: 

- https://github.com/Automattic/wp-calypso/issues/83453

**Comment by cuemarie** [comment]
I've created the label itself: [[Feature] Support Links](https://github.com/Automattic/wp-calypso/labels/%5BFeature%5D%20Support%20Links)

**Comment by jeherve** [comment]
Fixed in D127190-code
