### ISSUE TITLE
Update Activity Log label and add feature to Bugomattic to route to wp-calypso

### ISSUE THREAD

**Issue by cuemarie** [Automattic/bugomattic#169]
### "What": What is your idea?

Convert [Activity Log](https://github.com/Automattic/wp-calypso/labels/Activity%20Log) to `[Feature] Activity Log` and have issues for this feature land in the wp-calypso repo, still under the `[Plugin] Jetpack` or `Jetpack` "feature group".

### "Why?": Why would this be impactful?

Right now, searching for "Activity Log" in Bugomattic results in the following:

![Markup on 2023-10-30 at 13:44:34](https://github.com/Automattic/bugomattic/assets/27249804/5d3d42f7-3611-4617-975a-6fb92936351f)

However, the Activity Log UI lives in Calypso.  Issues related to the Activity Log would still want to be filed under the "Jetpack" view in the One Board, so we'd want the labeling to be `[Feature] Activity Log` & `[Plugin] Jetpack` so it appears there.

Example issue: https://github.com/Automattic/wp-calypso/issues/83534

**Comment by jeherve** [comment]
done in D127188-code.
