### ISSUE TITLE
[Feature] Related Posts missing from Bugomattic

### ISSUE THREAD

**Issue by cuemarie** [Automattic/bugomattic#170]
### Quick summary

We have a label [[Feature] Related Posts](https://github.com/Automattic/jetpack/labels/%5BFeature%5D%20Related%20Posts) in the Jetpack repo, but Bugomattic doesn't have this feature in its list. 

### Steps to reproduce

1. Start at Bugomattic home
2. Report a bug
3. Type "Related Posts"

![Markup on 2023-11-03 at 10:02:44](https://github.com/Automattic/bugomattic/assets/27249804/34c88dc6-60d7-4f35-b6cc-f7bdab67e115)

### Browser

Mozilla Firefox

**Comment by jeherve** [comment]
Done in D127940-code.
