### ISSUE TITLE
Remove Support Docs Content issues from The One Board 

### ISSUE THREAD

**Issue by cuemarie** [Automattic/bugomattic#173]
### Quick summary

When a new `Support Docs Content` bug/request is filed via Bugomattic, those issues are reported correctly in the `/en.support-docs-content` repo, but they are incorrectly being added to The One Board.  That project addition should be removed.

### Steps to reproduce

1. Start at Bugomattic
2. File a bug/feature request with the Feature: `Support Docs Content`

![a4bkTA.png](https://github.com/Automattic/bugomattic/assets/27249804/ea536e60-2c1f-4a94-aa47-d681516756d2)

3. Open the new report in GH and observe the **Projects** field

![3IKVUO.png](https://github.com/Automattic/bugomattic/assets/27249804/126a8ac7-ee1f-46b2-8ad5-d9c146629f25)

4. To compare, then go to https://github.com/Automattic/en.support-docs-content/issues/new/choose and **Get Started** on the top issue
5. Observe that we don't need to add a project to these new issues.

### Browser

Mozilla Firefox

**Comment by jeherve** [comment]
Done in D130040-code.
