### ISSUE TITLE
Update Bugomattic Footer

### ISSUE THREAD

**Issue by cat-og** [Automattic/bugomattic#174]
### "What": What is your idea?

The current Bugomattic footer reads "Got questions or need help? Hop in #kitkat in Slack and reach out!"
We'd like to update that to read "Got questions or need help? Hop in #dotcom-pa-triage in Slack and reach out!"

<img width="1097" alt="Markup 2023-11-27 at 22 45 33" src="https://github.com/Automattic/bugomattic/assets/86028337/3b4a5117-830d-4a32-a8ea-c53712e8621a">

### "Why?": Why would this be impactful?

The #kitkat in Slack is no longer monitored, and the #dotcom-pa-triage is now the best channel at which to reach out.

**Comment by jeherve** [comment]
Done in D130125-code
