### ISSUE TITLE
KitKat's Slack channel is referenced under Jetpack

### ISSUE THREAD

**Issue by crweiner** [Automattic/bugomattic#175]
### Quick summary

I noticed that the #KitKat Slack channel is referenced when trying to find a team to contact regarding Jetpack bugs. I noticed it under Jetpack -> Other, but there may be multiple locations where #KitKat is referenced which would need to be updated.

Marking as `[Pri] Normal`, but do feel free to adjust as necessary! 😄 

### Steps to reproduce

1. Start at Buggomattic home
2. Go to "Report an Issue," Type -> Bug
3. In "Product and Feature" choose Jetpack -> Other
4. Next steps has a section that says:

> Notify the #kitkat channel that you couldn't find a matching feature
We'll make sure the configuration data gets updated!

### Browser

Google Chrome/Chromium

### Other notes

Similar to #174

Screenshot:

![Markup on 2023-11-28 at 12:42:50](https://github.com/Automattic/bugomattic/assets/23106097/1e51e011-6ff3-41ea-af0d-9c97c3f90511)

**Comment by jeherve** [comment]
Done in D130267-code.
