### ISSUE TITLE
Wrong P2 link for Origami team

### ISSUE THREAD

**Issue by mattsherman** [Automattic/bugomattic#180]
### Quick summary

Using Bugomattic, I found that it is using the wrong P2 link for Origami. It is using +teamorigami, which points to a non-a8c site (DCVl-p2), instead of +teamorigamip2, which points to the correct P2 (efbwt-p2).

### Steps to reproduce

1. Go to Bugomattic
2. Report an Issue
3. Search for Storefront > Storefront
4. Continue
5. Verify that +teamorigami is suggested, and goes to wrong site (non-a8c P2)

**Comment by jeherve** [comment]
Fixed in D142435-code
