### ISSUE TITLE
[Feature] Copy a Post

### ISSUE THREAD

**Issue by vajrasar** [Automattic/bugomattic#190]
A user [has requested a feature](https://wordpress.com/forums/topic/wordpress-publishing-suggestion-or-please-direct-me-where-i-can-make-one/?view=all#post-4053512) to add the option to duplicate a page or post in the Editor sidebar.

The user suggests placing the duplicate option next to the URL copy option that appears when the page/post is published.

I propose that we implement the option as the user suggested, and also include the option in the editor sidebar where we show the post or page status.

**Comment by jeherve** [comment]
I added an issue here to keep track of this idea:
https://github.com/Automattic/jetpack/issues/38449
