### ISSUE TITLE
[Bug]: Ask in Slack first(WordPress.com > WPCOM Store & Purchases > Checkout)

### ISSUE THREAD

**Issue by Robertght** [Automattic/bugomattic#209]
### Quick summary

We need to ping in Slack in #payments before submitting an issue

### Steps to reproduce

When reporting a bug, search for checkout and pick  WPCOM Store & Purchases > Checkout

![Image](https://github.com/user-attachments/assets/88aed8e1-b77b-410c-991c-85eb667a6bb6)

Same thing with Domains:

![Image](https://github.com/user-attachments/assets/f026e67d-eaf3-4e13-8a56-d29e3c15c88c)

Could we review if these are still relevant nowadays?

cc @jeherve and thank you in advance!

**Comment by jeherve** [comment]
> When reporting a bug, search for checkout and pick WPCOM Store & Purchases > Checkout

This is probably a question for the Payments guild, at +paymentsguild. @caimin-j Where do you prefer Bugomattic to point when folks want to report bug reports and enhancement requests for payment-related features? Slack or GitHub, and if GitHub, which repo and which label?

Thank you!

> Same thing with Domains:

That would probably be a question for the folks on the Domains guild, at +dmngld. Their p2 seems to indicate Slack as the first point of contact. @aisajib Could you confirm?

**Comment by aisajib** [comment]
> Could we review if these are still relevant nowadays?

> Their p2 seems to indicate Slack as the first point of contact


That's correct, @jeherve / @Robertght. To ensure high visibility, we recommend a Slack call with `@domains-help` first in dotcom-support (not in the domains channel). If something seems off or buggy, a domain guilder can investigate further, post on storep2, or ping Nomado for help.

**Comment by caimin-j** [comment]
Pinging @jromales, lead of the Payments Guild, to confirm the best answer to @jeherve's [question](https://github.com/Automattic/bugomattic/issues/209#issuecomment-2490793884).

**Comment by jromales** [comment]
> Pinging [@jromales](https://github.com/jromales), lead of the Payments Guild, to confirm the best answer to [@jeherve](https://github.com/jeherve)'s [question](https://github.com/Automattic/bugomattic/issues/209#issuecomment-2490793884).

Thanks for the ping @caimin-j ! 

@jeherve @Robertght Yes, this process is still relevant. By pinging in the #payments Slack channel, our payments developers can review the issue and either guide folks in the right direction or open the GitHub report.

**Comment by jeherve** [comment]
Thank you all. Closing this issue then, since Slack remains the good point of contact for those issues.
