### ISSUE TITLE
[Bug]: Incorrect publish dates on /blog homepage

### ISSUE THREAD

**Issue by sailerbe** [Automattic/bugomattic#212]
### Quick summary

Incorrect publish dates are appearing on the featured post area of the /blog homepage. [This post](https://wordpress.com/blog/2024/12/11/snow-time-like-the-present-for-wordpress-com/) published today (Dec. 11) but the date displays as Dec. 4:

![Image](https://github.com/user-attachments/assets/f7356deb-6aab-46d3-9e6e-1d0240e9b461)

### Steps to reproduce

1. Visit the /blog home page
2. Check the publish date displayed in the Featured post section

### Browser

Google Chrome/Chromium

### Other notes

@Noemish @briowill I've added you as assignees because I think this would get routed to you but please let me know if someone else should be looped in.

**Comment by briowill** [comment]
Published fix in 155371-ghe-Automattic/wpcom-a8c-themes
