### ISSUE TITLE
[Task - Reporting Flow]: Add keywords to the selected feature details in feature selection step.

### ISSUE THREAD

**Issue by dpasque** [Automattic/bugomattic#55]
### Details

pciE2j-1VQ-p2#comment-1674

### Checklist

- [ ]

**Comment by karenroldan** [comment]
Hey @john-legg regarding the design when adding keywords to the selected feature, I see that the breadcrumbs will no longer be displayed. What is the intended display for the completed step; should we retain the breadcrumbs there? 

I might have missed it in Figma, but let me know what you think! 

**Expected design**

![Screenshot 2023-04-18 at 14 58 25](https://user-images.githubusercontent.com/67279475/232784899-c49d64c0-f1dd-466b-8a76-11eacd86bfc2.png)

**Current completed step**

![Screenshot 2023-04-18 at 14 57 36](https://user-images.githubusercontent.com/67279475/232784662-5a704f9b-9644-4b8e-b3db-8a6c11dc6900.png)

**Comment by john-legg** [comment]
@karenroldan I'm so sorry. I'm not sure why I didn't see this! I'm glad you pinged me in Slack 😅

**Comment by karenroldan** [comment]
> @karenroldan I'm so sorry. I'm not sure why I didn't see this! I'm glad you pinged me in Slack 😅

No problem! 👍🏻
