### ISSUE TITLE
[Task - Reporting Flow]: Add support for JIRA tickets

### ISSUE THREAD

**Issue by dpasque** [Automattic/bugomattic#85]
### Details

Tumblr uses them - we should add a task type for this!  👍  Probably need to reach out to Tumblr to get the details of how they do that issue tracking

### Checklist

- [ ]

**Comment by karenroldan** [comment]
Useful links on how to report a bug on Tumblr
- PCYsg-Aw1-p2
- PeJxwm-w-p2
