### ISSUE TITLE
[Task - Other]: Bring Tracks events and logging up to date

### ISSUE THREAD

**Issue by dpasque** [Automattic/bugomattic#91]
### Details

The app has changed a lot! It's time to go back over our Tracks events, and add any new needed ones or deprecate ones that don't make sense anymore.

Similarly, we should look to see if we're missing logging anywhere.

### Checklist

- [ ] Review old Tracks events. Deprecate as needed.
- [ ] Add new Tracks events.
- [ ] Review and confirm the Tracks events in the events directory in MC
- [ ] Review for new places to add logging.

**Comment by karenroldan** [comment]
- Review old Tracks events. Deprecate as needed -- handled in #107. Context: pciE2j-27d-p2
- Add new Tracks events. -- handled in #108. Context: pciE2j-27d-p2

**Comment by dpasque** [comment]
We did this!
